name: final_project_2023
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  firedart: 0.9.0+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  get: 4.6.5
  firebase_auth: ^4.2.5
  flutter: 
    sdk: flutter
  cloud_firestore: ^4.3.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - lib/assets/logo/trash.png
    - lib/assets/logo/login.png
    - lib/assets/logo/search.png
    - lib/assets/logo/note.png
    - lib/assets/gambar/jns.jpg
  uses-material-design: true

