// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqP4FGbo0-qGrK6Yj4v2gBbs58dOxNAAs',
    appId: '1:331126653598:web:5084ace5e4afa77569f18f',
    messagingSenderId: '331126653598',
    projectId: 'finalproject-8bedc',
    authDomain: 'finalproject-8bedc.firebaseapp.com',
    storageBucket: 'finalproject-8bedc.appspot.com',
    measurementId: 'G-CC28BB4YK0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_KSGwVBKiBRIKuzqyGPCPj_LmSFZ2y3g',
    appId: '1:331126653598:android:b5e77229eec0812769f18f',
    messagingSenderId: '331126653598',
    projectId: 'finalproject-8bedc',
    storageBucket: 'finalproject-8bedc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJLTthsIWULn6AsnEi3Qqt5btrxOkKong',
    appId: '1:331126653598:ios:102e7e2f98341f9569f18f',
    messagingSenderId: '331126653598',
    projectId: 'finalproject-8bedc',
    storageBucket: 'finalproject-8bedc.appspot.com',
    iosClientId: '331126653598-tlolnphip0gm9pt56ps6f85kregijdk5.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProject2023',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJLTthsIWULn6AsnEi3Qqt5btrxOkKong',
    appId: '1:331126653598:ios:102e7e2f98341f9569f18f',
    messagingSenderId: '331126653598',
    projectId: 'finalproject-8bedc',
    storageBucket: 'finalproject-8bedc.appspot.com',
    iosClientId: '331126653598-tlolnphip0gm9pt56ps6f85kregijdk5.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProject2023',
  );
}
